### ISSUE TITLE
Get it to work

### ISSUE THREAD

**Issue by lggwettmann** [d-harel/raindrops#1]
Sorry guys, I feel like a newbie, but I just can't seem to get it working.

Here a Fiddle http://jsfiddle.net/xs8rt74L/2/

I created a div and initiated the jquery plugin on that div's id - but nothing happens. Any more documentation on that perhaps?

The plugin looks great on your demo site - good job and thanks for your work.

**Comment by d-harel** [comment]
Hi there!
Two problems caused this not to work:
a. The plugin uses jQuery UI.
b. The element must have width & height. 
Check out the fix to your problem:
http://jsfiddle.net/caroqom8/1/

I felt this should be documented so I've added it to the website. Thank you for pointing it out.

Daniella

**Comment by lggwettmann** [comment]
Thanks, Daniella :+1: works like a charm!
